### ISSUE TITLE
missing instructions

### ISSUE THREAD

**Issue by Santanachia** [KartoffelToby/better-thermostat-ui-card#10]
there is no information how to enable it.
I've downloaded it via HACS and don't know what to do next.

**Comment by KartoffelToby** [comment]
First, i like to make clear that this is a addon for the ai_thermostat (better_thermostat). It might work with other climate devices, but i didn't get support for issues on other climates.

1. Install ai_thermostat in HACS
2. Setup your ai_thermostats (look in the README of ai_thermostat)
3. Go to your lovelace dashboard, and add a new Card, choose Better Thermostat UI Card
4. Select your ai_thermostat climate entity
5. Click add
