### ISSUE TITLE
In cooling mode, the blue and white colors should be swapped on the rotary track

### ISSUE THREAD

**Issue by kbrown1016** [KartoffelToby/better-thermostat-ui-card#102]
### Current behavior:

**Figure1**
![image](https://user-images.githubusercontent.com/35518748/232600104-ff86ae79-6f26-4267-bb01-b766917a5b32.png)
In the above Figure1, the use of colors during "heating" mode is logical and correct.  The non-white color (orange, in this case) indicates the zone in which the HVAC will "turn on" (by heating, in this case)

**Figure2**
![image](https://user-images.githubusercontent.com/35518748/232599228-a69832f9-ddb8-4135-9cf5-6143a4598cc6.png)
In the above Figure2, the use of colors is wrong.

### Expected behavior:

**Figure3**
![image](https://user-images.githubusercontent.com/35518748/232599602-4a0431eb-7125-4021-b594-b49e3856ce19.png)
In the above Figure3, I've (crudely) mocked up how the colors should be swapped compared to Figure2.  This color swapping is desirable because it logically aligns with the use of colors in Figure1.  In Figure3, the non-white color (blue, in this case) would indicate the zone in which the HVAC will "turn on" (by cooling, in this case)

**Comment by KartoffelToby** [comment]
cooling mode isn't supported by BT Integration at this time, i'm working on it, keep an eye on the Integration

**Comment by kbrown1016** [comment]
> cooling mode isn't supported by BT Integration at this time

Could you please elaborate on this? How is it "not supported"?

**Comment by KartoffelToby** [comment]
@kbrown1016 This card is a special card for https://github.com/KartoffelToby/better_thermostat it only works "correct" with this type of climate entities. currently i support only heating devices, but working on cooling devices too.
