### ISSUE TITLE
Color issues with theme.

### ISSUE THREAD

**Issue by custa1200** [KartoffelToby/better-thermostat-ui-card#105]
I am using the Noctis theme https://community.home-assistant.io/t/noctis-theme/163984 and notice that the colours on the thermostat are not working as expected. When heating the heating icon is grey as is the target temp ring.

<img width="431" alt="CleanShot 2023-05-08 at 12 52 08@2x" src="https://user-images.githubusercontent.com/161224/236723471-5ef8689c-f165-4d47-92aa-82858668f14f.png">

Maybe they others the unelected state and the current temp run maybe should be white instead of the gray? Not sure if this is something that needs to be fixed in this card to allow more consistent theming.

<img width="415" alt="CleanShot 2023-05-08 at 12 54 07@2x" src="https://user-images.githubusercontent.com/161224/236723769-9ef235d1-4bad-4f45-b4a3-c16a6c68abcb.png">

<img width="421" alt="CleanShot 2023-05-08 at 12 54 17@2x" src="https://user-images.githubusercontent.com/161224/236723776-c5eb20b2-50cd-4afb-8e90-29e0f925d0dd.png">

<img width="415" alt="CleanShot 2023-05-08 at 12 54 26@2x" src="https://user-images.githubusercontent.com/161224/236723778-c177149b-a25f-4439-a79b-f3eab11aee54.png">

<img width="415" alt="CleanShot 2023-05-08 at 12 54 36@2x" src="https://user-images.githubusercontent.com/161224/236723784-4ac927f6-a25a-4f6f-8ed4-9cc790f4d895.png">

**Comment by Spegeli** [comment]
I use the noctis theme too and have the same issue. Any solution?

**Comment by KartoffelToby** [comment]
Color problems should be fixed in 1.0.5

**Comment by custa1200** [comment]
I am still having color issues

**Comment by KartoffelToby** [comment]
@custa1200 looks like you using it with a non bt entity, at this time i'm only Support bt entities
