### ISSUE TITLE
Scaling and HA frontend issues since v2.0.0

### ISSUE THREAD

**Issue by Eyco1981** [KartoffelToby/better-thermostat-ui-card#115]
The new card (v2.0.0) has some scaling issues. This is one inside of a grid card:
![climate2](https://github.com/KartoffelToby/better-thermostat-ui-card/assets/88980079/30191d89-b581-4445-8b3c-3b47dcdd9543)
Additionally it breaks the Home Assistant frontend's details page for climate entities.
![climate](https://github.com/KartoffelToby/better-thermostat-ui-card/assets/88980079/4e0a21a9-c7dd-410c-9df8-6839a034e30a)

**Comment by Harrdy** [comment]
i confirm this. It not only destroys the detail page of climate entities. It also destorys the detail page of light entities.

the chrome dev console show me this error.

Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "md-focus-ring" has already been used with this registry
logging-mixin.ts:80 Error during logging error: undefined Error: Cannot parse given Error object
    at Object.parse (error-stack-parser.js:35:23)
    at stacktrace.js:106:62
    at new Promise (<anonymous>)
    at fromError (stacktrace.js:105:20)
    at t (log-message.ts:37:31)
    at logging-mixin.ts:70:27

**Comment by kerimcelik** [comment]
I confirm the problem. I had to restore a few times before I noticed this problem. 
![Screenshot_2023-09-20-08-18-38-755_io homeassistant companion android](https://github.com/KartoffelToby/better-thermostat-ui-card/assets/2659309/061a15e3-f8e3-490c-9dd8-9403846164c8)

**Comment by MicEs1** [comment]
First: Thank you very much for the new Update! "Better Thermostat" and the corresponding UI Card are an awesome additions to home assistant. :-)

I have exactly the same issue with the Update to 2.0.0:
- Better Thermostat 1.3.0-beta seams to run fine (besides a real test is outstanding as its too warm now for heating)
- as soon as I install better-thermostat-ui-card 2.0.0 I lost access to the details page for climate entities.
- As soon as i restore Version 1.1.1 the details page for climate entities are back (with the old layout of course).

If needed I am able to install better-thermostat-ui-card 2.0.0 again and can get Logs. For now I am back on V. 1.1.1.

**Comment by alghofaily55** [comment]
hi , i fet same issus after update ,, also when i remove it breaks the Home Assistant frontend's details page for climate entities.

what i can do ??

**Comment by Eyco1981** [comment]
Reverting to v1.1.1 and refreshing the browser cache (Ctrl + F5) fixes it.

**Comment by KartoffelToby** [comment]
Fixed with 2.1.0

**Comment by KartoffelToby** [comment]
@hayvan96 can you provide more Infos.
which Browser?
which grid?

**Comment by Eyco1981** [comment]
![1](https://github.com/KartoffelToby/better-thermostat-ui-card/assets/88980079/eae727d3-5d3b-4d4c-a0e5-4975c83fff0a)
Grid card in Chrome

![2](https://github.com/KartoffelToby/better-thermostat-ui-card/assets/88980079/78f0a17d-5bac-42cf-99d5-417dff963f2d)
Grid card in HA Companion app

**Comment by KartoffelToby** [comment]
@hayvan96 Thanks for your feedback, with that i figure out some issues, can you check it again with 2.1.1?

**Comment by KartoffelToby** [comment]
@hayvan96 yaks, sry for that struggle, hope 2.1.2 will do it for you :)

**Comment by Eyco1981** [comment]
With 2.1.2:
![ui](https://github.com/KartoffelToby/better-thermostat-ui-card/assets/88980079/2a0342fc-5bc5-4bb9-8102-467cac0177d6)
Upper left: all enabled
Upper right: + and - disabled
Lower left: +, -, heat, eco and off deactivated
Lower right; +, -, window and summer deactivated

**Comment by hayvan96** [comment]
@KartoffelToby with 2.1.2

![image](https://github.com/KartoffelToby/better-thermostat-ui-card/assets/37040583/6c4b247d-f69e-4d31-b1f8-cacbce4d49b5)

**Comment by Eyco1981** [comment]
Still having scaling issues as soon as the heating, eco and off buttons are hidden.
