### ISSUE TITLE
Seeing this warning in my logs: "update_hvac_action' was never awaited"

### ISSUE THREAD

**Issue by ovizii** [KartoffelToby/better-thermostat-ui-card#117]
I am on the latest HA as of right now and have just updated BT and the BT card. All seems working but I see this in my logs:

```
  update_hvac_action(self)
2023-09-21 10:38:55.147 WARNING (MainThread) [py.warnings] /config/custom_components/better_thermostat/utils/controlling.py:85: RuntimeWarning: coroutine 'update_hvac_action' was never awaited
  update_hvac_action(self)
```

**Comment by KartoffelToby** [comment]
https://github.com/KartoffelToby/better_thermostat/issues/1061

Wrong repo ;)

**Comment by ovizii** [comment]
Sorry for posting in the wrong repo, and thanks for linking to the related issue, I'll keep an eye on that link.
