### ISSUE TITLE
Card doesn't refresh/update when entity state changes

### ISSUE THREAD

**Issue by travisterrell** [KartoffelToby/better-thermostat-ui-card#120]
Hello,

It seems as though this card does not reliably update when the state is changed through another mechanism. 

E.g. if I use the Better-Thermostat card to set the temperature to 78, then use either a different card or the wall thermostat controls to adjust the setpoint, the Better-Thermostat card does not seem to reflect the change. My other thermostat cards do update when the value is adjusted on the Better-Thermostat card, as expected, but the inverse does not happen.

Any thoughts on what might be causing this? 

Is it a bug in the card, or just something I'm overlooking in how its supposed to work? I wasn't able to find another issue that reported this. (If it is a bug, I'm not immune to work, so if somebody can point me in the right direction, I may be able to fix it and make a PR.) 

Thanks,
Travis

**Comment by KrX3D** [comment]
i got a simular problem. When i set the mode to OFF with another mechanism, than the card still shows HEAT. its probably the same problem

**Comment by travisterrell** [comment]
> i got a simular problem. When i set the mode to OFF with another mechanism, than the card still shows HEAT. its probably the same problem

Hey, I actually figured this out, but forgot to close the card. User error after all. In my case, I didn't realize that I had duplicate entities for the same device, and had a different one set in each card. (One MQTT and one direct Z-Wave.) You might check to make sure you don't have a similar situation.
