### ISSUE TITLE
Summermode with DWD Integration Version 2.0.*

### ISSUE THREAD

**Issue by l-freund** [KartoffelToby/better-thermostat-ui-card#123]
Hi!
I'm using the DWD integration for weather data and to trigger summermode in Better Thermostat. There were changes in HA regarding weather integrations and the developers of DWD released a new version that is compliant with this. I reported my issue to them and they said, I should adress you because BT seems to not be compatibel to this new weather integration standard: https://github.com/FL550/dwd_weather/issues/88

I just realised, it is not an issue with BT itself but only with the BT UI card. Here is what happens:
When I update the DWD integration to this new Version 2.0.*,  my BT UI Cards are showing every TRV with summer mode enabled despite the reported temperature beeing below the configured value. BT itself keeps working and is sending proper temperatures to the TRVs.

I'm using the latest version of BT (1.3.0), BT UI Card (2.1.3) and HA (2023.10.0). Tests were however made with 2023.9.3.

Regards
Lutz

**Comment by cpktmpkt** [comment]
I had the same problem with dwd weather 2.0.4 a change to openweathermap as weather forecast provider solved the problem so it's probably an issue with dwd.

regards
christian

**Comment by 1Tomber** [comment]
Just had the same problem, changed one BT to use DWD location and I got summer mode and additionally strange behaviour like in this issue: https://github.com/KartoffelToby/better_thermostat/issues/913

Also after removing the dwd entity, my min max temps for that BT are now 7-35 C°, which were 5-25°. Using Tado Homekit TRVs.

**Comment by alexba1** [comment]
Hi I confirm the summer mode behaviour with DWD integration. 
br 
Alex

**Comment by l-freund** [comment]
Solved with BT 1.5.1 and the use of the new weather API.
