### ISSUE TITLE
Only on Firetablet w. Fully Browser: Custom element doesn't exist: better-thermostat-ui | type: custom : better-thermostat-ui-card 

### ISSUE THREAD

**Issue by ranseyer** [KartoffelToby/better-thermostat-ui-card#129]
![Fire-Tablet-Fully](https://github.com/KartoffelToby/better-thermostat-ui-card/assets/3889328/95414be3-efc9-4f08-b020-1c92ac61c575)

Hi,

thanks for this great software. Since some day we need heating again. 

A) The "better-thermostat-ui-card" works on all devices...
B) But not on the FireTablet with Fully Browser. Last year this combination also had worked. on the tablet i got the error like shown in the picture.

In the logs is see this:

`/config/custom_components/better_thermostat/utils/controlling.py:85: RuntimeWarning: coroutine 'update_hvac_action' was never awaited update_hvac_action(self)
19:09:31 – (WARNUNG) Better Thermostat (benutzerdefinierte Integration) - Die Nachricht ist zum ersten Mal am 18:55:05 aufgetreten und erscheint 5 mal
The unit of sensor.ew_dewpoint (°C) cannot be converted to the unit of previously compiled statistics (Â°C). Generation of long term statistics will be suppressed unless the unit changes back to Â°C or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
18:55:10 – (WARNUNG) Sensor - Die Nachricht ist zum ersten Mal am 18:55:10 aufgetreten und erscheint 5 mal`

I would be happy for any hints...

**Comment by dennker6** [comment]
I literally fought the same problem yesterday. Is it an older firetablet? Then the Webview ist probably outdated. If you can access it via the Fire Toolbox, you can just sideload it and set in as preferred renderer in Fully kiosk.

**Comment by ranseyer** [comment]
> I literally fought the same problem yesterday. Is it an older firetablet? Then the Webview ist probably outdated. If you can access it via the Fire Toolbox, you can just sideload it and set in as preferred renderer in Fully kiosk.

Thank you very much. I found and installed Amazon System WebView_112.amazon-webview-v112-5615-tv.5615.197.49
Now its fine !
