### ISSUE TITLE
Dutch translation (NL)

### ISSUE THREAD

**Issue by Dynamix72** [KartoffelToby/better-thermostat-ui-card#17]
`{
    "common": {
        "version": "version"
    },
    "extra_states": {
      "window_open": "Raam open",
      "night_mode": "Nacht mode",
      "summer": "Zommer"
    }
  }`

**Comment by KartoffelToby** [comment]
Please create a PR

**Comment by KartoffelToby** [comment]
will be in 0.1.1

**Comment by TheDukeSr** [comment]
`"Zommer"` is spelled wrong. Should be `"Zomer"`
