### ISSUE TITLE
The string line goes outside the picture when there is additional information

### ISSUE THREAD

**Issue by m-novitsky** [KartoffelToby/better-thermostat-ui-card#18]
![image](https://user-images.githubusercontent.com/46490655/147394759-36da5b9e-8fc4-42bf-9f6e-0d0b4353e66b.png)

New line in 'text' tag of svg needed.
Maybe use `<tspan>` to split strings?

**Comment by KartoffelToby** [comment]
I also thinked about icons, future versions of ai_thermostat will replace the single night mode with a modes array so maby icons are the better way

**Comment by m-novitsky** [comment]
Yes, it makes sense. Translations can be too long.

**Comment by IronButterfly** [comment]
<img width="383" alt="Screenshot 4" src="https://user-images.githubusercontent.com/24541086/148580722-be4ced06-cea4-4441-b33a-0d276fd8b484.png">

Indeed. Looks terrible. And why there is Лето (Summer) instead of Winter?

**Comment by m-novitsky** [comment]
> Indeed. Looks terrible. And why there is Лето (Summer) instead of Winter?

Yeahh, the same with me.
