### ISSUE TITLE
Ability to control fan state

### ISSUE THREAD

**Issue by bobloadmire** [KartoffelToby/better-thermostat-ui-card#24]
Not sure if this is in the scope of this project, but I have been searching high and low for a card that has a ui element to control just the fan state on my Ecobee Thermostats. Sometimes I don't want heat or AC, I just want circulation to even out the home humidity.

**Comment by KartoffelToby** [comment]
No, i didn't plan to add a fan control for now, but humidity will be displayed in future versions
