### ISSUE TITLE
Extra text after latest update

### ISSUE THREAD

**Issue by tungmeister** [KartoffelToby/better-thermostat-ui-card#26]
I've just updated to the newest version and now I'm seeing the "summer" text as shown below:
![image](https://user-images.githubusercontent.com/127809/148596238-f3ace12a-588f-4ce2-9987-0bc9bd404274.png)
can I remove this?

**Comment by KartoffelToby** [comment]
Yes, its a kind of a bug, we currently rename the ai_thermostat HACS to better_thermostat and changes some code stuff, in the final version of 1.0 of better thermostat Summers will be only shown if the setup outdoor temp is reached
