### ISSUE TITLE
[Bug]? some thermostat types used for better_thermostat do not show current temperature in better_thermostat_ui_card (but do in the standard thermostat card)

### ISSUE THREAD

**Issue by bsafh** [KartoffelToby/better-thermostat-ui-card#37]
Some thermostat types used for better_thermostat do not show current temperature in better_thermostat_ui_card (but do in the standard thermostat card)

**better_thermostat 1.0.0-beta15**

**OK: working example: Homematic HM-CC-DN-RT**

![image](https://user-images.githubusercontent.com/106388187/189527432-ced0bf46-c96f-4ac0-b901-9e09f0311a84.png)

![image](https://user-images.githubusercontent.com/106388187/189527441-78fce2ac-3c9a-480a-84d5-15c86fbce029.png)

![image](https://user-images.githubusercontent.com/106388187/189527471-8f4dd6b6-da44-411d-a1e3-5b0a536fb9ab.png)

```
type: custom:better-thermostat-ui-card
entity: climate.trv_ai_bad_gaeste_2
name: Bad Gäste

```
![image](https://user-images.githubusercontent.com/106388187/189527554-57b94780-c68b-4dfb-bdde-96ece2be821f.png)

**Not OK: non-working example: Moes BHT002-GALZB**

![image](https://user-images.githubusercontent.com/106388187/189527612-5f3389e8-c133-4a90-8fa0-5c384893d8b7.png)

![image](https://user-images.githubusercontent.com/106388187/189527638-cef64ad6-8ea1-4027-85bb-129c229fa169.png)

![image](https://user-images.githubusercontent.com/106388187/189527644-4a2d9f29-4946-4c6b-9185-42dee998c243.png)

```
type: custom:better-thermostat-ui-card
entity: climate.trv_ai_bad_unten
name: Bad unten
```
![image](https://user-images.githubusercontent.com/106388187/189527666-76aafd89-3ef6-4d09-822a-2d899099626d.png)

Standard thermostat card works: (with the physical thermostat)

![image](https://user-images.githubusercontent.com/106388187/189527881-bba08d61-d948-4885-9344-b22af4c0d888.png)

not with the better_thermostat:
![image](https://user-images.githubusercontent.com/106388187/189527914-29216142-846f-42c9-b888-b9661e03c696.png)

**2nd non working example: Eurotronics Comet DECT**

![image](https://user-images.githubusercontent.com/106388187/189527708-4ba76572-6c5e-476b-a8d2-7e3b421e3acc.png)
![image](https://user-images.githubusercontent.com/106388187/189527726-43a4a855-fc07-4055-9bef-be8a020f546a.png)
![image](https://user-images.githubusercontent.com/106388187/189527746-1aaba307-0971-4b0e-8041-057838fbcc4a.png)
![image](https://user-images.githubusercontent.com/106388187/189527763-545a5203-5990-44d9-83cd-1cc2bbef1b29.png)
![image](https://user-images.githubusercontent.com/106388187/189527785-e592f02e-31c0-4939-9c91-7e57fcf1ae5d.png)

```
type: custom:better-thermostat-ui-card
entity: climate.trv_ai_wc_oben
name: Thermostat WC oben
```
Standard Thermostat card works:

![image](https://user-images.githubusercontent.com/106388187/189527818-112b0db6-a917-49f3-aade-656b7fdc37c2.png)

(with the physical thermostat, not with the better_ui_thermostat for it)

**Comment by KartoffelToby** [comment]
@bsafh 0.2.0 and beta 18 work fine for me

**Comment by submarcos** [comment]
Same problem for me. Tested with last release and master version

**Comment by KartoffelToby** [comment]
pls test 0.9.0
