### ISSUE TITLE
Add unit text to target temp, add a "now:" or "target:" descriptor before respective temp

### ISSUE THREAD

**Issue by Exynom** [KartoffelToby/better-thermostat-ui-card#41]
What I never liked about the built-in climate card, is that I find it very unintuitive to have two temperatures displayed in the card with no descriptor to let us know what's what. To increase the confusion, the _current temperature_ sits in the middle of the slider that actually sets the _target temperature_.. Adding any of these should be a quick html fix and greatly improve [WAF](https://en.wikipedia.org/wiki/Wife_acceptance_factor) ;)

**Comment by KartoffelToby** [comment]
Take a Look at 0.5.0 it got a lot of WAF

**Comment by Exynom** [comment]
Indeed, thanks a ton! :)
