### ISSUE TITLE
not able to trigger/test the automatic functions of the integration

### ISSUE THREAD

**Issue by mortalone** [KartoffelToby/better-thermostat-ui-card#43]
so. im trying to figure out how this integration works. and i cannot trigger it to start heating if i drop the room temperature via developer tools.

the thermostat wil not turn on heating. as i would wxpect it to do. in order to reach the desired temperature.

and the other way arround. if i use the companion lovelace UI card. and set desired room temperature to a much higher temperature. the thermostat is not turned on either.

it is detecting summer, wich could explain things. but is it possible to trigger/alter the season if that is whats preventing me from testing. ?

**Comment by KartoffelToby** [comment]
If you want to test it, you must "fake" the weather or Outdoor Sensor temps, but you should know, it uses the avg of the Last 2 days. And collect this infos only once a day and on Startup.

So the best Thing you can do to test it is set the  off temp on Outdoor temp to 25-30°C in the device settingt of BT (restart ha after that)

**Comment by mortalone** [comment]
so i set the temperature to 26degrees on the outdoor cutoff limit.

and i was expecting some kind of alteration in the ui.

after reboot. the better thermostat entity is off. then i turn up the desired room temperature. and i was somehow expecting the thermostat to turn on.

perhaps im not fully aware what the extension does.

i did read the text on this page.
https://github.com/KartoffelToby/better_thermostat/blob/242b55ca452cdbcf17717f6183f0e0b528ba1799/README.md

and it says "Your weather forcast provider will turn your heat on/off"
