### ISSUE TITLE
ECO or Away modes?

### ISSUE THREAD

**Issue by auanasgheps** [KartoffelToby/better-thermostat-ui-card#44]
Hello!

First, let me thank you for this **terrific** combination (component + card) to manage TRVs in a very SMART way.
I just purchased some TS0601 and done the whole integration. Hopefully everything will work fine, winter season is not yet here.

I have my cards ready to go. Can I setup away or ECO modes?
I see the ECO mode icon (leaf) but how do I use it? And what about Away mode and the "sun mode (?)" i see in the card?
![image](https://user-images.githubusercontent.com/20586878/194012455-0cbb454a-dadd-44ef-a47e-03a37082f988.png)

I'm planning to do some automations but would be great to reference these modes instead of individual temperatures.

**Comment by edgardavim** [comment]
Some of the automations you can do via YAML. For example set external temperature (weather.home for example) to work or the hours it should work or not.

currently, with all updates, and starting to re-use this winter, I have not yet been able to make anything work :D It ignores all the yaml data.

**Comment by auanasgheps** [comment]
Okay, but what's the plan about ECO and Away temperatures? Can I set them somewehere and call a service to enable the specific mode via automations?

**Comment by KartoffelToby** [comment]
I didn't know what you mean by yaml config, BT is a config flow Integration.

Anyway yes it's possible to set night,away or Eco modes via Services: https://better-thermostat.org//schedule

**Comment by KartoffelToby** [comment]
@auanasgheps  the sun icon is shown when the Outdoor temp is over the set temp in your config (summer mode) heating is off

**Comment by auanasgheps** [comment]
@KartoffelToby thanks. So I simply enable the "alternative" mode by calling "better_thermostat.set_temp_target_temperature" and the other to restore the usual temperature?

**Comment by KartoffelToby** [comment]
Yes

**Comment by auanasgheps** [comment]
Thanks for clarifying. Closing.

**Comment by ovizii** [comment]
> @auanasgheps the sun icon is shown when the Outdoor temp is over the set temp in your config (summer mode) heating is off

thanks, I've been wondering how that works for a while :-)
