### ISSUE TITLE
Improvement: Design adjustments

### ISSUE THREAD

**Issue by Ecronika** [KartoffelToby/better-thermostat-ui-card#45]
I would suggest a few changes:

1.) Display window and summer status in the circle to make the display more compact.

2.) Show unit behind the target temperature. Make unit display configurable.

3.) Buttons - and + for incremental temperature adjustment without the circle.

4.) Eco mode to the modes off / heating and make usable, calls the services Set Temporary Temperature and Restore Temperature in the background. In this context, the Eco mode should have a default temperature, which can be used without specifying an individual temperature in the configuration of the Better Thermostat integration.

5.) Display the current mode at the bottom and make it switchable by option to save space.

![btcard](https://user-images.githubusercontent.com/112566758/194626825-f55f12ad-3bc7-42b1-a8cd-066c7da6dd6b.png)

**Comment by KartoffelToby** [comment]
thanks for the feedback, i will think about it.  I have already adjusted a few things in 0.5.0

**Comment by Ecronika** [comment]
A few updated thoughts on version 0.7.0:

1.) The window and summer mode make a good impression in the new position - but would it be possible that these are only displayed when the status is active? For example, I don't have window monitoring in the bathroom and the inactive symbol is therefore always unnecessary. If it were only displayed with the window open, no configuration or knowledge of the BT settings would be necessary for the correct display.

2.) The display of temperature and humidity is very successful, but I don't have a humidity sensor in one of my rooms - here the temperature is not displayed in the middle, but slightly offset, it may be that an empty field for the missing humidity is causing this ?

3.) With the slightly larger touch surface on the circle, I probably no longer need the + and - buttons, it also seems to work quite well on the smartphone.

4.) The manually selected Eco-Mode apparently starts at 18°C ​​- can this temperature be adjusted? I was thinking of a configuration in BT as the standard eco temperature, which is always selected when you run the service without a target temperature.

5.) Just leave out the text, the symbols are sufficient for me. But I noticed that Heat and Off have a mouseover text and Eco doesn't - that could possibly be added.

**Comment by KartoffelToby** [comment]
4. Yes take a look in the readme you can Override the Default value with eco_temperature in the card config

**Comment by Ecronika** [comment]
Something went wrong with the translation in the current version...

Previously, "current" was correctly translated to "Aktuell" in German. Now it remains English.

**Comment by KartoffelToby** [comment]
@Ecronika yes it's confusing, there are several vars set by ha, looks like they changed Something.

Try to select Englisch, and than Back to German, should fix it

**Comment by Ecronika** [comment]
Yes, now it is translated ...

Small visual (final) "problem": when the window contact is off and the summer mode is shown in the middle, it looks slightly offset to the left - the problem is visual, not technical, and is due to the sun's peaks being off-centre . Maybe it would be better to use "mdi:weather-sunny"?

**Comment by KartoffelToby** [comment]
Let me take a look at the Icon, the sun with the temp indicator is in my eyes a good Symbol for, too hot outside.


With the color, this can be an soulution, but what color shoud i use for in heating but idel?

I want an other color than of, to prevent confusion

**Comment by Ecronika** [comment]
according to a traffic light possibly yellow "wait for change"?

**Comment by KartoffelToby** [comment]
It think the most improvements are done since version 2. feel free to open a new issue
