### ISSUE TITLE
New design problem on Firefox browser

### ISSUE THREAD

**Issue by itanczos** [KartoffelToby/better-thermostat-ui-card#46]
Hello KartoffelToby,
thank you for your hard work!
I am using the latest UI version and there is a problem with the display under the Firefox browser.
![image](https://user-images.githubusercontent.com/411455/195334038-f85f8b26-673e-489f-bd95-0523663ead71.png)

It displays correctly in the Chrome browser:
![image](https://user-images.githubusercontent.com/411455/195334210-30b4f099-e026-4967-9737-0242e71d5ba6.png)

**Comment by itanczos** [comment]
On Safari:
![image](https://user-images.githubusercontent.com/411455/195579374-7649aff2-3475-4fe8-8d95-bb13afed77dc.png)

**Comment by Christoph-Wagner** [comment]
The new version 0.8.0 that’s supposed to fix those issues broke the UI even more for FF (Chrome is still fine):

![image](https://user-images.githubusercontent.com/1609329/195980786-ed4e650d-482a-4cbb-a569-6d6c9e30ab90.png)

**Comment by KartoffelToby** [comment]
What a Glitch 😅

I'll Check it soon

**Comment by arough007** [comment]
Since I think this is related I will add my problem here.
Since 0.8.0 my cards look like this on iOS.
The HA app, Chrome and Safari are all the same.
So I guess it's a webkit problem on iOS?
![54C41170-E243-4C66-BBDE-E6E770146964_1_201_a](https://user-images.githubusercontent.com/55582932/196005965-2219d805-aed9-413f-9d5c-9cf9df6b3764.jpeg)

**Comment by pbranly** [comment]
Hi
On my side, with the HA applet, I don't have the temperature setting on my iphone while I have it on my Ipad

**Comment by KartoffelToby** [comment]
@arough007 yes its an apple webkit problem, sadly i haven't any apple devices here, can you debug it?

@Christoph-Wagner this glitch should gone with 0.8.1

**Comment by arough007** [comment]
Yes of course.
Just tell me what to do.

On my Mac it's working okay, if that helps.

**Comment by CryPt00n** [comment]
Can also assist, Mac & iPhone here

**Comment by Christoph-Wagner** [comment]
> @Christoph-Wagner this glitch should gone with 0.8.1

Nice, the glitch is gone, though there’s still a small issue, the humidity doesn’t fully fit and gets cuts off on both sides:

![image](https://user-images.githubusercontent.com/1609329/196879639-f991bf59-f212-4051-8b01-924a66eb15ab.png)

**Comment by KimHEF** [comment]
> > @Christoph-Wagner this glitch should gone with 0.8.1
> 
> Nice, the glitch is gone, though there’s still a small issue, the humidity doesn’t fully fit and gets cuts off on both sides:
> 
> ![image](https://user-images.githubusercontent.com/1609329/196879639-f991bf59-f212-4051-8b01-924a66eb15ab.png)

I changed the humidity to rounded percentages in z2m to make it fit...
But in iOS 16 the set_temperature is missing.

**Comment by KartoffelToby** [comment]
fixed in 0.9.0
