### ISSUE TITLE
Brt-100 UI issue

### ISSUE THREAD

**Issue by pbranly** [KartoffelToby/better-thermostat-ui-card#47]
Hi 
- When restarting HA, standard thermostat is off but is working as a slave of BT ----> strange but ok
- In this state the fact to toggle heat off in the BT thermostat does not change the status of normal thermostat ----> strange but OK
- When changing the status of the normal thermostat to heat, the fact to toggle the BT from heat off heat, off etc ..is then taken in account by normal thermostat ---> strange but nearly OK as it can hide a side effect
- the BT eco mode is fully inactive . I am quite sure it worked 2 days ago. Then I have added outside external temperature. This could be the reason ? ----> NOK

Phil

**Comment by KartoffelToby** [comment]
Thats not normal, the ui should Display unavailable as long as BT isn't completly started

**Comment by KartoffelToby** [comment]
think this issue is related to the intigration
