### ISSUE TITLE
Cool button

### ISSUE THREAD

**Issue by RASBR** [KartoffelToby/better-thermostat-ui-card#48]
Hi,
Did I miss something in the changes during update. Can't find a way to show the cool button like before!!

Now:

`type: custom:better-thermostat-ui-card
entity: climate.gf_office_ac
disable_window: true`

![Better Thermostat](https://user-images.githubusercontent.com/63133627/196057968-c3047783-4565-4ace-8340-d2268dae3a3c.jpg)

My AC unit is Daikin connected via KNX integration

Thanks in advance

**Comment by KartoffelToby** [comment]
This component is Focus on an addition to Better thermostat,

So i didn't plan any Support for other devices at the moment

**Comment by RASBR** [comment]
I see. Thanks for the clarification
