### ISSUE TITLE
climate_group entity always summer/missing extra values?

### ISSUE THREAD

**Issue by Soukyuu** [KartoffelToby/better-thermostat-ui-card#49]
I'm 90% sure it's because the climate_group does not pass the underlying values beyond temp/hvac_mode, but since it's the recommended way to group better_thermostat entries: Is it possible to fix this, or is the only way to leave it in always/disable summer?

**Comment by KartoffelToby** [comment]
The ui Card isn't compatiple with climate group

I Work on an native group function for BT
