### ISSUE TITLE
other set_temperature on the hardware thermostat

### ISSUE THREAD

**Issue by tomg1970** [KartoffelToby/better-thermostat-ui-card#50]
I have installed better thermostat via hacs.
So far it worked without any problems. But now I have the problem,
that when setting the 'set_temperature' via the dashboard a different
value is displayed as on the hardware thermostat itself.
The value changes, but currently always by a difference of 5 degrees.

Better thermostat: 20 degrees
MOES TS0601: 25 degrees

And if I change a temperature on the MOES thermostat, this change is not
visible on the better thermostat

**Comment by KartoffelToby** [comment]
pls open an issue on better_thermostat, this isn't a ui bug
