### ISSUE TITLE
0.8.1 issue in iOS App

### ISSUE THREAD

**Issue by buhralex** [KartoffelToby/better-thermostat-ui-card#51]
I just updated to UI-card 0.8.1 and it seems there is a problem in the iOS companion app. 

The font is to big.

iPhone 11 w/ iOS 16.0.3

![34C65C5C-0DA8-410E-98F8-08AB75A2E946](https://user-images.githubusercontent.com/6676113/196601358-d32fda74-c6c4-4f56-a5e6-00eccc2f00fa.jpeg)

**Comment by pbranly** [comment]
I don't have the temperature setting with my iphone
It is ok on my Ipad
Phil

**Comment by augard** [comment]
I have the same problem with macOS Safari.

**Comment by KimHEF** [comment]
Same with iPhone 12 Pro - iOS 16.0.2

**Comment by dragonat0r** [comment]
The same with iPhone - iOS 15.7
Missing set temperature.

**Comment by edgardavim** [comment]
Same with ipad 

![79D07111-A84A-4814-B6B4-616C33B3E7C2](https://user-images.githubusercontent.com/35406114/197415252-e8c4f6eb-8e57-4543-896f-e78af6c9f547.jpeg)

**Comment by KartoffelToby** [comment]
Found the issue, some stuff i used is not Support by Apple


Sadly this is often an issue and a real pain for Developer, anyway i found an soulution but i need to rewrite a lot of stuff. This will tanke some time

Thanks all for the Feedback so far

**Comment by KartoffelToby** [comment]
Checkout version 0.8.2

its possible that a little bit of alignment is still needed
