### ISSUE TITLE
installment

### ISSUE THREAD

**Issue by Quidamdk** [KartoffelToby/better-thermostat-ui-card#54]
how do i install this add on? cant get it working

![image](https://user-images.githubusercontent.com/113060910/197724246-b29bd6a9-f537-4079-b81a-6b1706440602.png)

**Comment by pbranly** [comment]
Under HACS interface 
![39008E98-39FB-4238-8B23-0D50DFEA4673](https://user-images.githubusercontent.com/22018509/197725274-8455641c-290a-45cf-92b1-ee46b55b0036.png)

**Comment by Quidamdk** [comment]
![image](https://user-images.githubusercontent.com/113060910/197729013-c9a53dd0-0268-4ab1-9f2a-b425cc67841f.png)
 and then im back, no install options, and cant open card or anything without getting back to first post.
 
do i need to add something to frontend ?

**Comment by KartoffelToby** [comment]
Your Screenshot is.cut off.

But your issue is an HACS issue, normaly it should be a Download Button in the right bottom Corner ![Screenshot_20221102-003954.png](https://user-images.githubusercontent.com/8983030/199362267-9d082cdd-bbf2-4b38-8116-31ac3c731fa0.png)
