### ISSUE TITLE
Fritz Dect301

### ISSUE THREAD

**Issue by Benne007** [KartoffelToby/better-thermostat-ui-card#55]
Can you provide better support for Fritz! Include Dect301 thermostat?

**Comment by KartoffelToby** [comment]
What doesn't Work?

**Comment by Benne007** [comment]
It doesn't work for me with the eco mode or I'm doing something wrong. can you give me an example ?

**Comment by Benne007** [comment]
Problem hat sich erledigt nach dem Video von Simon42. Danke
