### ISSUE TITLE
current temperature alignment

### ISSUE THREAD

**Issue by tungmeister** [KartoffelToby/better-thermostat-ui-card#58]
Hi, my temperature is aligned to the left however as no humidity is provided by the climate entity I'm using. could the card align the current temperature centrally when no humidity is available?
![image](https://user-images.githubusercontent.com/127809/199712882-7f804b70-49f6-447f-bf6b-d0d224cd9082.png)

**Comment by KartoffelToby** [comment]
@tungmeister fixed in 0.9.0
