### ISSUE TITLE
Contols resizing (or hide option)

### ISSUE THREAD

**Issue by dlsnet** [KartoffelToby/better-thermostat-ui-card#6]
Hi. Is there a change you fix the issue with controls buttons which don't resize with the card? Or provide an option to hide them? Thank you. 

![image](https://user-images.githubusercontent.com/3121405/146664236-a32e1bc2-be80-4e0a-8ddb-dc9f21e57254.png)

**Comment by KartoffelToby** [comment]
This is in the first place an addition for the ai_thermostat intigration, it will be work with other climates to but my Focus will be on devices with two modes.

as i wrote in the readme, its early in development. So this Kind of issues will be fixed in the next weeks

**Comment by KartoffelToby** [comment]
such small viewport are not supported, but in 0.9.0 the responsive options are back
