### ISSUE TITLE
No option for cooling-only systems

### ISSUE THREAD

**Issue by dustin-l-brown** [KartoffelToby/better-thermostat-ui-card#60]
Works great for integration with nest or similar thermostats.  I don't see an option to set it for cooling.  So instead of a red fire icon when the "heat" is on, i'd like to see a snowflake, like the standard thermostat.

**Comment by KartoffelToby** [comment]
Because this isn't a General supported climate Card. Its for better thermostat Intigration

Anyway if i had time, i like to add an "normal" mode for other Intigrations. But this isn't on prio

**Comment by KartoffelToby** [comment]
UPDATE: i plan add a flag to this card, so than it can be used by other climates as well and not only for BT, anyway, i also plan to add cooling devices support for BT too

**Comment by Giuliointhetube** [comment]
> UPDATE: i plan add a flag to this card, so than it can be used by other climates as well and not only for BT, anyway, i also plan to add cooling devices support for BT too

It would be great if you can add entities lice Air Conditioners and trigger them when the temperature goes above the setpoint.
Adding the option to select which entity should be triggered provides flexibility for those that are trying to make multiple devices work together even if are not compatible with smart thermostats (it saves money).
Adding a low-temperature cursor to the interface should be cool. 
If you need a beta tester I'm available to play around with it and provide feedback. Thanks!

**Comment by KartoffelToby** [comment]
Pls keep an eye on the progress for cooling in the BT Integration repo, this will be closed for now
