### ISSUE TITLE
UI-Improvements

### ISSUE THREAD

**Issue by kimme1024** [KartoffelToby/better-thermostat-ui-card#62]
Hi,

I'm following this development for over a year now and I'm glad to see it's coming close to it's completion.
For me personally there are 2 UI improvements that would make the card perfect:

- Switch the current and target temperature location:
As I'm using 7 virtual thermostats (1 per room) which are all automated for target temperature I really don't care about that specific value. I'm only using the cards so I can have a quick view of the current temperatures around the house when I look at my wall mounted tablets on each floor. Therefore I'd like to have the current temperature displayed as the biggest value in the center of the card. Anyway I think that the most important value that has to be visible is the current temp instead of the target temp as the last one doesn't change that much.

- Use (invisible) chevrons to change the target temperature:
Not all touchscreens are that responsive. That makes setting the target temperature a hassle to have it perfect. Also, when using WallPanel as your dashboard makes setting the temperature via the bar refresh the page as it detects a pulldown to refresh.
A better way would be the implementation used by the Dark Thermostat Card which activates chevrons up and down the card on touch to change the temperature. It would also make sense to add the possibility to define the increments of temperature when changing the target temperature. You'd want to display the exact temp (to 0.1°C) but only want to change the target temp with 0,5°C.

As an extra (but this is not really related to the card itself) it might be interesting to explore the possibilities of a PID related thermostat as you already include the outside temperature in your config. This would really make it the "best" thermostat ;)

**Comment by ElStupid** [comment]
Agree this. The generic thermostat card also displays the current temperature as the biggest one, so this is a bit confusing.
I can understand why it has been implemented like this, because the "current" block also shows the current humidity.

**Comment by kimme1024** [comment]
> Agree this. The generic thermostat card also displays the current temperature as the biggest one, so this is a bit confusing.
> I can understand why it has been implemented like this, because the "current" block also shows the current humidity.

I can also perfectly understand the decision designwise. However it's just not relevant to show the target temp as the main, biggest value as you know what you've set (automated) it to. Maybe just show the target temp briefly when changing it and restore to the current temp after x-seconds, next only show the humidity beneath the line...

**Comment by ElStupid** [comment]
For me, it's okay to show the target temperature, I would be interested in that. So just swapping current and target would be good for me. If one isn't interested in the target temperature, it would be nice to have it as a setting like "disable_target_temperature"

**Comment by OrbitingOcelot** [comment]
I also disagree with this proposal. For me just like for @ElStupid the main info on a thermostat is what it is set to, so it makes sense to have it in a visually prominent place.  I dont really care what the currently measured temp is, so a small info next to humidity is perfectly fine for me.

**Comment by KartoffelToby** [comment]
A Option for swap should possible, but its complicated with the humidity

I think there wasnt a right or wrong its a Personal preferences

**Comment by OrbitingOcelot** [comment]
Agreed, its a matter of preference. And yeah, more options are always nice to have ;)

**Comment by ElStupid** [comment]
I think I'm misunderstood :) I do agree with the proposal. I also want to see the target temperature, but not as the biggest one.
Opposite of @OrbitingOcelot I know what the target temperature is (my smart home takes care of that). So, the first thing I want to see is the current temperature.

**Comment by KartoffelToby** [comment]
One question, if the swap target with current Position is set to true, what happend with the humidity?

**Comment by kimme1024** [comment]
> One question, if the swap target with current Position is set to true, what happend with the humidity?

The humidity can stay at its current position in my opinion. As for the target temp next to it you can label it above the line.
If you don't like the fact that the 2 values are next to each other, maybe just remove the target temp all together and replace the current temp with the target temp while changing it, reverting back to the current temp after 15sec.

**Comment by OrbitingOcelot** [comment]
I also set the temp automatically, but give the users the option to override - hence it is useful for me (and users) to see the set temp. Just out of curiousity, if you set everything automatically and always know what the target temp is, why do you even need a thermostat card? Why not just a temp sensor, much cleaner..

**Comment by kimme1024** [comment]
> I also set the temp automatically, but give the users the option to override - hence it is useful for me (and users) to see the set temp. Just out of curiousity, if you set everything automatically and always know what the target temp is, why do you even need a thermostat card? Why not just a temp sensor, much cleaner..

You’ve answered your own question before you’ve asked it :) to be able to manually override.

About any normal thermostat displays the current temperature as main value. So why reinvent the wheel?

I’m having room specific heating. That means I’m having 7 virtual thermostats. 
For example it’s handy to be able to see the current temperature in my son’s room when he’s asleep in case something might have gone wrong with an automation/sensor/whatever. I know the temp it should be, I want to know that it effectively is that desired temp.

**Comment by ElStupid** [comment]
> Just out of curiousity, if you set everything automatically and always know what the target temp is, why do you even need a thermostat card? Why not just a temp sensor, much cleaner..

The thermostat is in fact the temperature sensor of course. I could use another card for that, but being able to override is exactly the thing. As wat @kimme1024 says, every other thermostat displays the current temperature as the main value. 

I see value in both use cases, so again, a setting would be very welcome :)

**Comment by OrbitingOcelot** [comment]
> You’ve answered your own question before you’ve asked it :) to be able to manually override.

Not really. He wrote he knows what the temp is because it gets set automatically, whereas I wrote that I set it automatically but it can be overriden, so I don't always know what the set temp is. In his reply he now mentions override, which implies not always knowing the target temp (unless you memorize it after every change 😂...), and the use cases are quite similar after all ;)

> About any normal thermostat displays the current temperature as main value. So why reinvent the wheel?
..
> every other thermostat displays the current temperature as the main value

Maybe I misunderstand what you mean, but to me this sounds completely wrong. All thermostats listed as supported by this project display ONLY the target temp. Many other thermostats have that set as the main/default value (e.g. Google Nest).

But I agree with your conclusion, value in both use cases, more customization options are always welcome!

**Comment by KartoffelToby** [comment]
![0 0 0 0_9123_lovelace-test_default_view](https://user-images.githubusercontent.com/8983030/203427100-3a1cc001-7b0e-446d-bf32-8e49f2aa3046.png)

working on a complete rewrite, to fix the responsive issues, and added some extras, what to you think?

Shoud i implement, the current/target switch button or just display current big, and target little, and show the target temp big while changeing?

**Comment by pbranly** [comment]
Hi
The + and - are good idea because the rotating button is too much sensitive
Target temp should be the biggest ( this is what is interesting)
Current temperature from external sensor ( in house) should be smaller . It is for me informative only
And KISS ! 
Phil

**Comment by ElStupid** [comment]
@KartoffelToby Good thing you are working on it. 

However, it's impossible to make it satisfactory for everyone. Your best bet would be to make it adjustable with some more settings I think.

For me:
- opposite of @pbranly and agreeing with @kimme1024, I would like the current temperature as big, the target small. This is (in my experience) just like you would expect from any hardware thermostat. Glancing at it, you see the current temperature and while rotating or setting, the target is displayed. The other way around is confusing for most people in my opinion.
- While I see the use for it, the - and + buttons clutter up the display. There's too many icons now to keep it clean. Would it be possible to make the endpoint of the ring clickable? So when clicking on the right end it acts like a + and on the left like a -. 
- Show a small - and + to keep it simple (indeed @pbranly ) by reversing the colors. In this example a white sign on a transparent background would look much cleaner.
- what is the heat symbol between the - and + doing?

**Comment by pbranly** [comment]
Hi agree and not !
but this is more philosophy than technical 
In my house if I set 19 deg it is because I want 19 deg. And I will be fine and make confidence with my central heating and all the stuffs 
If I set 19 deg and I see 18 deg in bold character I will be cold 
This is the reason why I think that the bold one should be the reference temp.

nevertheless If I consider my Nest thermostat, the standard default screen is the ambient temperature …
So … let hear other points of view and proceed with a vote !
phil

**Comment by KartoffelToby** [comment]
@ElStupid its the idle/heating indicator

**Comment by OrbitingOcelot** [comment]
Hi @KartoffelToby!
Agree with @pbranly :
1. Target temp should be big, it's the main value - same as with any other hardware TRV ;)
2. KISS - I personally would rather not have fancy transitions, values swapping places etc.

**Comment by ElStupid** [comment]
> 1. Target temp should be big, it's the main value - same as with any other hardware TRV ;)
> 2. KISS - I personally would rather not have fancy transitions, values swapping places etc.

1. Divided opinions, two camps :-) If you could make this a setting, I think you solve the issue.
2. Agree to @OrbitingOcelot. What I stated earlier about changing to target when rotating: it's what most hardware thermostats do, not what this card should do

**Comment by kimme1024** [comment]
> ![0 0 0 0_9123_lovelace-test_default_view](https://user-images.githubusercontent.com/8983030/203427100-3a1cc001-7b0e-446d-bf32-8e49f2aa3046.png)
> 
> working on a complete rewrite, to fix the responsive issues, and added some extras, what to you think?
> 
> Shoud i implement, the current/target switch button or just display current big, and target little, and show the target temp big while changeing?

Sorry for the late reaction. I broke my foot yesterday so I was in the hospital.

For me the second option would be the most logical. So current big, target little and only big when manually changing.
You can take a look at the dark thermostat card for the implementation of the chevrons. It’ll make the card less cluttered.

As for the main discussion. I think the different opinions relate to trvs vs room thermostats. I can see why you’d want to see the target temp as biggest value when using it to control trvs. However if you’d want to use it as a room thermostat it really should display the current temp as main value imo.

**Comment by KartoffelToby** [comment]
Just dropped 1.0 hope you all enjoying the new Options and style. 

The + - Thing isn't in there but looking Forward for 1.1 ;)

**Comment by ElStupid** [comment]
Looks good @KartoffelToby 👍 Are there any new options? The changelist was gone before I finished reading and I can't seem to find it anymore.

**Comment by kimme1024** [comment]
> Just dropped 1.0 hope you all enjoying the new Options and style.
> 
> The + - Thing isn't in there but looking Forward for 1.1 ;)

I just installed it for the first time as it's coming close to completion so I can start to test it and migrate my system afterwards.
Sadly I'm running into some issues for which I've made a feature request on the integration part. I hope it'll make sense. If not feel free to contact me.

**Comment by OrbitingOcelot** [comment]
Thanks @KartoffelToby , great work! 🦾
btw, not sure if it's an issue on my side, but the button to adjust the temp is HUMUNGOUS...
Is that supposed to be that way? Any way to make it smaller, and disable to growing/shrinking animation on mouseover?

![image](https://user-images.githubusercontent.com/67998808/203934389-0e45da9f-1f9a-4349-b01a-4e015a4609cd.png)

**Comment by ElStupid** [comment]
Is this the mouseover size? Without mouseover, the size on my end is like this
![image](https://user-images.githubusercontent.com/5188875/203941901-fb1f4806-0a5c-4f88-b89c-6723db64026f.png)

**Comment by KartoffelToby** [comment]
With version 2 the ui changed alot, feel free to open a new issue if i missed something
