### ISSUE TITLE
BT-UI-Card breaks editing of other cards on dashboard

### ISSUE THREAD

**Issue by OrbitingOcelot** [KartoffelToby/better-thermostat-ui-card#64]
Hi, something strange is going on, sometimes the BT-UI card seems to be "rendered out of its visual bounds", which means I cannot interact with of edit other cards on the same dashboard. I have added a video to demonstrate, as this is difficult to explain. You will see I am unable to click "edit" in the card above.

[btui.zip](https://github.com/KartoffelToby/better-thermostat-ui-card/files/10089812/btui.zip)

**Comment by Tom-ahawk** [comment]
I have a similar problem with the custom:tabbed-card, - it does not respond anymore with the BT-UI in it.
Having two tabs, one tab the thermostat the the other with heating settings. 
![1](https://user-images.githubusercontent.com/35527507/204144348-8e202d97-cc2c-4803-8fbb-590508958a1f.gif)
![2](https://user-images.githubusercontent.com/35527507/204144358-77248fb3-d3ad-49fe-ac74-7652a0dc4a81.gif)
