### ISSUE TITLE
ver 1.0 too big and cant edit card

### ISSUE THREAD

**Issue by kuduacz** [KartoffelToby/better-thermostat-ui-card#66]
in version 1.0 few things.

At 1st its too big to use imo.
2nd when all is disabled it look like that:
![image](https://user-images.githubusercontent.com/77231628/203957913-23d56521-2eb9-40c5-a44b-ad74e0787616.png)
3rd Cant edit card when there is other below that one.

**Comment by itanczos** [comment]
I have the same problem. Firefox, Chrome and Companion applications have the error.

**Comment by KartoffelToby** [comment]
since version 2 this shoudn't be a problem anymore
