### ISSUE TITLE
Cards only stacking vertically, hard to click correct button and more

### ISSUE THREAD

**Issue by arough007** [KartoffelToby/better-thermostat-ui-card#67]
I have a similiar issues to #66, but not quite.

The cards are really big and are now stacked vertically in the dashboard. Even when zooming out they won't rearrange to fill the screen and won't arrange on the horizontal axis.

The bottom buttons are there for me, but barely clickable.
When trying to click them the next card is highlighted.
The buttons controlling the actual card are all correctly clickable.

Also when swapping the target and actual temps it shows the actual temp in both.
This happens only on cards where there is no humidity curiously 🤔 
I have 2 cards with humidity and 2 without. The ones with humidity can be swapped, the other one produce the error seen below.

![Nov-26-2022 12-02-44](https://user-images.githubusercontent.com/55582932/204085752-0094c3b5-801f-42dd-bdf9-75a05fd8bbf2.gif)

**Comment by KartoffelToby** [comment]
Did you run 1.0.1?

**Comment by arough007** [comment]
Oh sorry. Yes this is on 1.0.1

**Comment by HA-TB303** [comment]
Same issue here, on 1.0.2
![image](https://user-images.githubusercontent.com/9609805/204138203-5aede6be-0c8d-46a4-8e32-ecdabaeca9db.png)

**I can not press any** of the buttons, except for the right hand top kebab., the thermostat name is gone and they are vertically stacked.

**Comment by arough007** [comment]
> Same issue here, on 1.0.2 ![image](https://user-images.githubusercontent.com/9609805/204138203-5aede6be-0c8d-46a4-8e32-ecdabaeca9db.png)
> 
> **I can not press any** of the buttons, except for the right hand top kebab., the thermostat name is gone and they are vertically stacked.

The names were gone for me as well, but you can add them back if you can hit the edit button.
Before I noticed, that there is a tiny portion that I can click I did this:

Click on the kebap of the card you want to edit and then click outside of the popup to close it again.
Then click tab a few times until `Edit` is higlighted and hit enter.


To add info to my issue:
I'm using Firefox on MacOS and Firefox on iOS normally.
I also tried Chrome on MacOS and Chrome and Firefox on Windows.
Same problem in every scenario.
But there is a small point at the very top of the edit button where I can click.

I'm on 1.0.2 and the error is still there.

**Comment by arough007** [comment]
The problem with clicking the buttons is fixed for me with 1.0.3
Vertical stacking is still there and swapping the temps still only shows the real temp in both.

But: progress 🎉  😄

**Comment by KartoffelToby** [comment]
sould be fixed in 2.1.0

**Comment by Oleg-Sob** [comment]
Thanks, I'll try. I solved this using layout-card.
