### ISSUE TITLE
what does this signify?

### ISSUE THREAD

**Issue by tungmeister** [KartoffelToby/better-thermostat-ui-card#68]
![image](https://user-images.githubusercontent.com/127809/204093052-cb391cd7-6552-443b-b84a-3a9bb1961d7c.png)

what does the highlighted indicator signify? Can't see anything in the documentation and can't interact with it?

**Comment by KartoffelToby** [comment]
It Shows the current Temperatur its an passive indicator

**Comment by tungmeister** [comment]
why is it higher than the set temperature then considering the actual temp is 14 as can be seen?

**Comment by KartoffelToby** [comment]
Good question, do you use it with the better thermostat Integrationen or is it a other climate entity?

**Comment by tungmeister** [comment]
I'm using it with another climate entity - the entity I'm using is correctly reporting current_temperature though which I assume this should be referencing.

**Comment by KartoffelToby** [comment]
Shoud be work on 2.1.0
