### ISSUE TITLE
Step size is 1 instead of 0.5

### ISSUE THREAD

**Issue by jjansen85** [KartoffelToby/better-thermostat-ui-card#69]
In latest releases the stepsize of the thermostat has changed to 1. Previously it was 0.5. 

I prefer to use the 0.5 resolution.

**Comment by Ditskys** [comment]
same, have stopped using untill 0.5 is brought in

**Comment by MagnavoxTG** [comment]
I would like it if we could configure this in some way because I prefer 1 degree steps but I understand that other might want finer control. I agree however, that 0.5 would be a good compromise.

**Comment by govido** [comment]
![image](https://user-images.githubusercontent.com/12106056/205721692-9a1c06b5-671b-494b-826c-31bb376b4a04.png)
Z-Wave Thermostat gives 0.1, lots of fun to adjust....

**Comment by KartoffelToby** [comment]
BT catch up the calibration steps from the real TRV from the ha device config.

So. The issue is deeper in ha

**Comment by KartoffelToby** [comment]
BT Supports Native groups. You shoud use this
