### ISSUE TITLE
Raise an event when manually changing temperature

### ISSUE THREAD

**Issue by ElStupid** [KartoffelToby/better-thermostat-ui-card#72]
## What is the feature?
I would like to see an event raised when the temperature has been set manually. 

### Description
I'm controlling my target temperature through a flow of custom conditions, which runs every 5 minutes. 
However, every now and then I would like to lower or raise the temperature. Then within 5 minutes my conditions come kicking in again and the target is being reset to whatever my automation flow decides. I'm using a switch now for "Manual temperature" so I can override the conditions. However, it would be much cleaner and nice to be able to set that switch whenever the temperature has been manually set. Thus an event which can be triggered in an automation.

### Additional Information
The event could be raised when using the temperature ring or some +/- buttons. Also, it could be useful to have the set temperature exposed by the event

**Comment by KartoffelToby** [comment]
its in 2.1.0, check it out!
