### ISSUE TITLE
Only one window sensor in setup Beta50

### ISSUE THREAD

**Issue by MaxGroh8684** [KartoffelToby/better-thermostat-ui-card#73]
Hi there first of all, in my opinion this will be the best Thermostat Control in HA ever.

My Issue here is, that i often want to stop heating depending on two or three windows and in two cases a door.

The Setup UI gives me chost the option to choose one sensor.

Is this a "layer 8 problem" or a bug?

**Comment by KartoffelToby** [comment]
@MaxGroh8684 
Sounds like the issue place is wrong, its not a real ui thing, its handle in the integration.

So you can add as many window sensor as you like, as long as you setup a HA Group for that:

Take a look at the readme of the integration: https://github.com/KartoffelToby/better_thermostat#example-windowdoor---sensor-config

**Comment by MaxGroh8684** [comment]
Hi Toby, sorry for that one. And thank you for pointing me in the right direction.
