### ISSUE TITLE
Temp gauge goes too high

### ISSUE THREAD

**Issue by mcneilc** [KartoffelToby/better-thermostat-ui-card#75]
This card is set up with a Moes valve. My other valves are Hive and they have a max temp of 32C. The card for the Moes valve goes all the way up to 300. I've deleted both the Better Thermostat valve and the card before adding them again but that's not made any difference

<img width="474" alt="Screenshot 2022-12-11 at 15 06 52" src="https://user-images.githubusercontent.com/1622985/206912326-8bd462b7-1d41-445d-920e-f1d6728fedef.png">

**Comment by hayvan96** [comment]
Same here, with a MOES TRV as well. I can't find where I can set the min/max for the gauge.

**Comment by xoozoo** [comment]
I've just had this issue and have been able to resolve it with a custom config for the TRV entity.

in the /config/configuration.yaml I added the following at the bottom of my file

```
homeassistant:
  customize: !include customise.yaml
```

Then create a file /config/customise.yaml

```
climate.dining_trv_thermostat:
    max_temp: 30
    min_temp: 5
```

Where climate.dining_trv_thermostat is the entity name of the trv thermostat that has this issue.
