### ISSUE TITLE
Still heating when above the target (BRT-100-TRV)

### ISSUE THREAD

**Issue by xHywel** [KartoffelToby/better-thermostat-ui-card#77]
Hello there, it seems i have a bug / incompatibility with my TRV's ? 

I have Moes TRV (model version > BRT-100-TRV) and Aqara / Xiaomi Temp sensors

![image](https://user-images.githubusercontent.com/96890351/206929392-08a708be-4ae6-4ff0-9e26-c9c1587a3427.png)

![image](https://user-images.githubusercontent.com/96890351/206929292-b4a2e09b-3a0c-4c93-8a0a-8d0d457fa345.png)

But it seems that it doesn't respect the target temperature, it was still heating when above the target, previousely set to 19° (I had to lower the target temp in the card in order to stop the heating) is it normal ? 

![image](https://user-images.githubusercontent.com/96890351/206929965-f7134c9c-8284-4ad9-9caf-1e313745920d.png)

+ I get the warning that my TRV is special because it doesnt support deactivate > Is it related ? 

Thanks in advance for your help and for this cool/useful integration !

**Comment by KartoffelToby** [comment]
Do you use local calibration?

Target Temperatur based should work 

The BRT is buggy device anyway (search in close issues)

**Comment by xHywel** [comment]
Thanks for your reply and explanations

Well sad.. I have four of these, if i knew this i wouldn't have bought them. Hope this could/will be fixed or mitigated.
They are popular because of some youtube videos + the price

If you have time do you have TRV recommendations ? I think that the list could also recommend TRV that are well functionning (and not only compatible). But I know thats time so thats just an suggestion amongs many others

**Comment by pbranly** [comment]
Hi
I know that many people don’t like this thermostat .
But I have 7 of this model and they work perfectly with better thermostat .
Don’t use calibration mode but temperature mode and you will be happy with. 

Phil

**Comment by xHywel** [comment]
> Hi I know that many people don’t like this thermostat . But I have 7 of this model and they work perfectly with better thermostat . Don’t use calibration mode but temperature mode and you will be happy with.
> 
> Phil

Hi Phil, thank you for your comments, i've seen some of your comments regarding these thermostats, helped me understand a little more about these TRV

Do recommend to use local calibration ? Do you have any other tip about them ? Im using Zigbee2mqtt
Is the option activate "child lock" still relevant ?

**Comment by KartoffelToby** [comment]
PLS reopen this issue in the main BT Repo, this is for the UI
