### ISSUE TITLE
French translation missing

### ISSUE THREAD

**Issue by pbranly** [KartoffelToby/better-thermostat-ui-card#80]
Hi
I can help for the French translation but cannot find the original file for this menu 
![62093044-E148-4095-A363-11E521D5CD01](https://user-images.githubusercontent.com/22018509/207123654-f2b49ebf-c968-4d65-b35d-997df094e2b4.jpeg)
Thanks 
Phil

**Comment by KartoffelToby** [comment]
Take a look at the en.json
