### ISSUE TITLE
Swapping current & target temperature not working

### ISSUE THREAD

**Issue by lthorpe18** [KartoffelToby/better-thermostat-ui-card#82]
The "Swap target with current temperature places" toggle doesn't seem to be working, it just displays the current temperature in both places, as per my attached screenshot:

![image](https://user-images.githubusercontent.com/76230477/207829635-d1a9a255-ca42-4e2f-ae8d-8247476e17df.png)

**Comment by richsimpson** [comment]
Yes same for me

**Comment by proadmin** [comment]
Same situation for me. Using both Nest thermostats and Pentair swimming pool controller.

**Comment by parislyon** [comment]
Same here

**Comment by nakedfoot** [comment]
Same here.
I chk the code and it seems to be correct, we should have a real swap, not only display of twice current temp.
I'm not dev, mayB it's not a big deal.

**Comment by godfreym29** [comment]
Can this be fixed please?

**Comment by prbreezy** [comment]
+1

**Comment by KartoffelToby** [comment]
Tested, and worked in 2.1.0

**Comment by mesistostefre** [comment]
Nope, still the same issue here. 

Thing is: if you **do not** have a **humidity** (sic!) sensor configured, the swapping current/target temp won't work.
If you **do** configure a humidity sensor, swapping the temps display works ...

This destroys my confidence in this thing. Will deinstall this card ...

**Comment by MStapelfeldt** [comment]
> "Swap target with current temperature places" toggle

Is there any documantation how this actually works? In Readme and settings I can't find a word about it. I know I did it once, forgot hwo to and can't make it work again...
