### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by seghide** [KartoffelToby/better-thermostat-ui-card#86]
Hi all. Could you maybe add "-" and "+" buttons on te left and right of the set ring? I'm just ending implementation of better thermostat at my home and would like to mount tablet as setting panel for my old grandma. I'm afraid that setting temperature via point on the ring will be to hard for her, so what's why I think ypu could add this kind of feature.

**Comment by raoulbhatia** [comment]
This would definitely be a worthwhile improvement!  Perhaps such a feature can be configurable i.e. if it should be enabled or the step-size?

**Comment by Bone84** [comment]
A Layout Like simple Thermostat would be nice. Sometimes I Change the Temperature with my Smartphone by accident, while scrolling.

**Comment by kbrown1016** [comment]
I 100% concur with this feature request.  Bump +/- buttons would be SO useful.  My family and guests would have an easier time setting the temperature.

**Comment by KartoffelToby** [comment]
Its landed in 2.1.0 :)
