### ISSUE TITLE
Fritz!Dect 301 Thermostat Home Assistant Log

### ISSUE THREAD

**Issue by Benne007** [KartoffelToby/better-thermostat-ui-card#88]
hi everyone,
Did I make a mistake or is my thermostat not supported? 
Better Thermostat seems to be running for me but I get this error message. I don't know what exactly the error is. Could you please help me.

Many Thanks

***************************************************************************************
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.better_thermostat.utils.bridge
Source: custom_components/better_thermostat/utils/bridge.py:31
Integration: Better Thermostat (documentation, issues)
First occurred: 09:12:32 (3 occurrences)
Last logged: 09:12:32

better_thermostat Better Thermostat WZ: intigration: fritzbox isn't native supported, feel free to open an issue, fallback adapter generic
better_thermostat Better Thermostat KU: intigration: fritzbox isn't native supported, feel free to open an issue, fallback adapter generic
better_thermostat Better Thermostat SZ: intigration: fritzbox isn't native supported, feel free to open an issue, fallback adapter generic

**Comment by KartoffelToby** [comment]
PLS reopen this issue on the BT Repo, this is for the UI only
