### ISSUE TITLE
Some cards are Red, Some Green? 

### ISSUE THREAD

**Issue by richsimpson** [KartoffelToby/better-thermostat-ui-card#89]
Not sure why, they slowly seem to all end up green. 

I use Tuya TS0601 valves. When I set up the integration or reload they are red, later they go green in no apparent order, maybe when a valve has been opened or closed via the BT integrations .

The valve mode when on (Auto/Heat swap enabled) is AUTO / MANUAL. 
The info shows that the valve is in HEAT (Off) mode - but is atually AUTO/MANUAL on the valve. 

When red the heat symbol shows, when green it doesnt, suggest eco mode but that is disabled on all of the items. 

![image](https://user-images.githubusercontent.com/51749826/212736317-a9028f2d-1da4-41ef-86a6-b4071a1b9f94.png)

green one
![image](https://user-images.githubusercontent.com/51749826/212736517-27e210e2-b39a-4d83-872c-c07201570c57.png)

red one
![image](https://user-images.githubusercontent.com/51749826/212736571-30db800c-6ca2-4800-83dd-085cd9c17955.png)

**Comment by KartoffelToby** [comment]
You use it with or without the BT integration?

Green means Eco Mode, red means Normal heating Mode.

If you are using it without BT green can also be Auto mode

**Comment by richsimpson** [comment]
Yes with the integration on all the items. 

They are in auto mode on TRV which is the heat/auto swap option.  But some decide to be red, Others green. It’s never in eco mode as that’s disabled and the actual trv is not in an eco mode at the time. Just straight forward auto. All of them are. 

Just odd they change from time to time. Right now they are all green. If I were using eco mode too, it would be handy to know if they are in that mode at a glance based on the colour but not reliable when some are green when not in eco. They stay green when heating too.

**Comment by Cook23** [comment]
If you select "heat" on green ones (the flame on bottom) they become red again. seems the mode is lost sometimes.
