### ISSUE TITLE
False position of current temperature

### ISSUE THREAD

**Issue by jbakermk** [KartoffelToby/better-thermostat-ui-card#90]
Note the current temperature, 11.5oC, is rendered in the wrong place. The range of the thermostat is 12-21. I suspect a one line code fix that doesn't render the current temperature if it is below the lowest temperature. I had a quick look but couldn't see the exact line.

![image](https://user-images.githubusercontent.com/26439619/214013787-0cdaf639-aab7-4b86-b726-af9c76659ab9.png)

**Comment by jbakermk** [comment]
The same bug happens if the thermostat reads a value above the maximum, as per below where the range is 12-21.

![image](https://user-images.githubusercontent.com/26439619/214561091-ea638789-136a-4cca-af44-b1771528dd30.png)

**Comment by KartoffelToby** [comment]
shoud be fixed with 2.1.0
