### ISSUE TITLE
Open window dont turn off my new Eurotronic TRV's

### ISSUE THREAD

**Issue by isibizi** [KartoffelToby/better-thermostat-ui-card#91]
Hello,

i have bought new Eurotronic TRV's. I have install it via ZHA and everything looks good in the UI. I have created an Better Thermostat and choose three TRV's in one room and configure in the option that the TRV don't have an off function. When i turn of the TRV's in the lovelace card, the TRV's turn off, but when i open the window, the TRV's don't turn off. I have tried it allready with Zigbee2MQTT, with Zigbee2MQTT the windows function works, but i have many other probelms. 

This are my TRV's **SPZB0001** has the same model name like the Eurotronic Spirit

![image](https://user-images.githubusercontent.com/73044043/214941351-462d6b2f-53eb-4353-801a-8d72c2d2775b.png)

**Comment by KartoffelToby** [comment]
This card only have all the "functions" if you use it with the Integration BT
