### ISSUE TITLE
Eco icon missing?

### ISSUE THREAD

**Issue by jonteriele** [KartoffelToby/better-thermostat-ui-card#97]
Hi,

Probably I am missing something but somehow I can not see the leaf icon for the ECO mode.
The toggles _Heat_ and _Off_ do work. The rest of the toggles don't.
What am I missing?

![image](https://user-images.githubusercontent.com/418951/220302905-68631e3c-97c2-43fb-8cba-0d10b774cb32.png)

**Comment by AchEgal** [comment]
Hello. Did you find any solution? I have exact the same problem.

**Comment by KartoffelToby** [comment]
This card is for the BT Integration, it only supports all functions if its used with the Integration
